Modules and dataset import

In [ ]:
!pip install pandas

In [1]:
import pandas as pd

df=pd.read_csv("../dataset/raw/Microclimate_dataset.csv")

In [2]:
df.head()

,cdTimestamp,Location_ID,Latitude,Longitude,LULC_Type,Temperature,Humidity,Wind_Speed,Solar_Radiation,Precipitation,Air_Pressure,NDVI
0,2022-01-01 00:00:00,Station_1,42.920785,-70.442076,Agricultural,-1.45,30.99,1.03,747.73,9,980.36,0.87
1,2022-01-01 00:05:00,Station_1,45.878954,-88.553180,Forest,24.93,58.33,9.05,297.29,0,1020.30,0.56
2,2022-01-01 00:10:00,Station_1,32.147619,-91.387175,Agricultural,20.60,74.46,8.63,549.58,2,1024.56,0.52
3,2022-01-01 00:15:00,Station_1,26.725934,-114.654620,Barren,3.09,65.30,7.90,755.51,10,1043.17,0.46
4,2022-01-01 00:20:00,Station_1,40.877759,-92.345482,Barren,17.44,44.88,11.49,979.98,1,998.33,0.47

Check column names

In [3]:
df.shape

(8640, 12)

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 8640 entries, 0 to 8639
Data columns (total 12 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   cdTimestamp      8640 non-null   str
 1   Location_ID      8640 non-null   str
 2   Latitude         8640 non-null   float64
 3   Longitude        8640 non-null   float64
 4   LULC_Type        8640 non-null   str
 5   Temperature      8640 non-null   float64
 6   Humidity         8640 non-null   float64
 7   Wind_Speed       8640 non-null   float64
 8   Solar_Radiation  8640 non-null   float64
 9   Precipitation    8640 non-null   int64
 10  Air_Pressure     8640 non-null   float64
 11  NDVI             8640 non-null   str
dtypes: float64(7), int64(1), str(4)
memory usage: 810.1 KB

In [5]:
df.columns.tolist()

['cdTimestamp',
 'Location_ID',
 'Latitude',
 'Longitude',
 'LULC_Type',
 'Temperature',
 'Humidity',
 'Wind_Speed',
 'Solar_Radiation',
 'Precipitation',
 'Air_Pressure',
 'NDVI']

check missing values

In [6]:
df.columns=df.columns.str.strip()

Check missing values

In [7]:
df.isnull().sum()

cdTimestamp        0
Location_ID        0
Latitude           0
Longitude          0
LULC_Type          0
Temperature        0
Humidity           0
Wind_Speed         0
Solar_Radiation    0
Precipitation      0
Air_Pressure       0
NDVI               0
dtype: int64

Check Duplicate records

In [8]:
print("Duplicate rows:",df.duplicated().sum())

Duplicate rows: 0

In [9]:
print(df.dtypes)

cdTimestamp            str
Location_ID            str
Latitude           float64
Longitude          float64
LULC_Type              str
Temperature        float64
Humidity           float64
Wind_Speed         float64
Solar_Radiation    float64
Precipitation        int64
Air_Pressure       float64
NDVI                   str
dtype: object

In [29]:
print(df.columns.tolist())
for col in df.columns:
    repr(col)

['cdTimestamp', 'Location_ID', 'Latitude', 'Longitude', 'LULC_Type', 'Temperature', 'Humidity', 'Wind_Speed', 'Solar_Radiation', 'Precipitation', 'Air_Pressure', 'NDVI', 'date', 'time']

Convert Timestamp properly

In [30]:
df["cdTimestamp"] = pd.to_datetime(df["cdTimestamp"], errors="coerce")
df["date"] = df["cdTimestamp"].dt.date
df["time"] = df["cdTimestamp"].dt.time

df[["date", "time"]]

            date      time
0     2022-01-01  00:00:00
1     2022-01-01  00:05:00
2     2022-01-01  00:10:00
3     2022-01-01  00:15:00
4     2022-01-01  00:20:00
...          ...       ...
8635  2022-01-01  23:35:00
8636  2022-01-01  23:40:00
8637  2022-01-01  23:45:00
8638  2022-01-01  23:50:00
8639  2022-01-01  23:55:00

[8640 rows x 2 columns]

In [31]:
print(df["date"].dtype)
print(df["time"].dtype)
print("Invalid date:",df["date"].isna().sum())
print("Invalid time:",df["time"].isna().sum())

object
object
Invalid date: 0
Invalid time: 0

In [32]:
print(df["NDVI"].head(20))
print(df["NDVI"].unique()[:20])

0        0.87
1        0.56
2        0.52
3        0.46
4        0.47
5        0.29
6        0.66
7        0.81
8         0.1
9        0.76
10       0.63
11       0.76
12       0.35
13       0.62
14    0.38git
15       0.19
16       0.31
17        0.7
18       0.55
19       0.71
Name: NDVI, dtype: str
<StringArray>
[   '0.87',    '0.56',    '0.52',    '0.46',    '0.47',    '0.29',    '0.66',
    '0.81',     '0.1',    '0.76',    '0.63',    '0.35',    '0.62', '0.38git',
    '0.19',    '0.31',     '0.7',    '0.55',    '0.71',    '0.17']
Length: 20, dtype: str

In [33]:
bad_ndvi = pd.to_numeric(df["NDVI"], errors="coerce").isna()

print("Invalid NDVI values:", bad_ndvi.sum())
print(df.loc[bad_ndvi])

Invalid NDVI values: 1
           cdTimestamp Location_ID   Latitude  Longitude LULC_Type  \
14 2022-01-01 01:10:00   Station_1  31.948236 -73.766292    Barren

    Temperature  Humidity  Wind_Speed  Solar_Radiation  Precipitation  \
14         1.21     39.06        0.64           885.92              8

    Air_Pressure     NDVI        date      time
14       1013.24  0.38git  2022-01-01  01:10:00

In [34]:
df["NDVI"] = df["NDVI"].astype(str).str.replace("git", "", regex=False)
df["NDVI"] = pd.to_numeric(df["NDVI"], errors="coerce")

In [35]:
print(df["NDVI"].dtype)
print("missing NDVI:",df["NDVI"].isna().sum())

float64
missing NDVI: 0

In [36]:
print(df["NDVI"].head(20))

0     0.87
1     0.56
2     0.52
3     0.46
4     0.47
5     0.29
6     0.66
7     0.81
8     0.10
9     0.76
10    0.63
11    0.76
12    0.35
13    0.62
14    0.38
15    0.19
16    0.31
17    0.70
18    0.55
19    0.71
Name: NDVI, dtype: float64

In [37]:
print(df.dtypes)

cdTimestamp        datetime64[us]
Location_ID                   str
Latitude                  float64
Longitude                 float64
LULC_Type                     str
Temperature               float64
Humidity                  float64
Wind_Speed                float64
Solar_Radiation           float64
Precipitation               int64
Air_Pressure              float64
NDVI                      float64
date                       object
time                       object
dtype: object

In [38]:
print("Invalid NDVI:", df["NDVI"].isna().sum())
print("NDVI below -1:", (df["NDVI"] < -1).sum())
print("NDVI above 1:", (df["NDVI"] > 1).sum())

Invalid NDVI: 0
NDVI below -1: 0
NDVI above 1: 0

In [39]:
print("Humidity below 0:", (df["Humidity"] < 0).sum())
print("Humidity above 100:", (df["Humidity"] > 100).sum())

Humidity below 0: 0
Humidity above 100: 0

In [40]:
print("Invalid latitude:", ((df["Latitude"] < -90) | (df["Latitude"] > 90)).sum())
print("Invalid longitude:", ((df["Longitude"] < -180) | (df["Longitude"] > 180)).sum())

Invalid latitude: 0
Invalid longitude: 0

In [41]:
print("Invalid timestamps:", df["cdTimestamp"].isna().sum())

Invalid timestamps: 0

In [42]:
print(df["LULC_Type"].value_counts())

LULC_Type
Urban           1775
Water           1755
Forest          1724
Agricultural    1715
Barren          1671
Name: count, dtype: int64

In [43]:
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])
print("Locations:", df["Location_ID"].nunique())

Rows: 8640
Columns: 14
Locations: 30

In [44]:
print(df.describe())

               cdTimestamp     Latitude    Longitude  Temperature  \
count                 8640  8640.000000  8640.000000  8640.000000
mean   2022-01-01 11:57:30    37.564648   -92.608464    12.514738
min    2022-01-01 00:00:00    25.000662  -124.999231   -10.000000
25%    2022-01-01 05:58:45    31.366795  -108.487303     1.225000
50%    2022-01-01 11:57:30    37.714368   -92.777086    12.420000
75%    2022-01-01 17:56:15    43.703949   -76.515592    23.840000
max    2022-01-01 23:55:00    49.999824   -60.000838    35.000000
std                    NaN     7.199839    18.747068    13.055157

          Humidity   Wind_Speed  Solar_Radiation  Precipitation  Air_Pressure  \
count  8640.000000  8640.000000      8640.000000    8640.000000   8640.000000
mean     60.303934     7.562444       547.501514       4.994792   1015.173694
min      30.010000     0.000000       100.050000       0.000000    980.030000
25%      44.997500     3.860000       321.130000       2.000000    997.610000
50%      60.530000     7.610000       548.460000       5.000000   1015.190000
75%      75.510000    11.310000       770.282500       8.000000   1032.805000
max      90.000000    14.990000      1000.000000      10.000000   1049.990000
std      17.446686     4.318258       261.446596       3.146476     20.309088

              NDVI
count  8640.000000
mean      0.502704
min       0.100000
25%       0.300000
50%       0.510000
75%       0.700000
max       0.900000
std       0.230648

In [46]:
df.head(20)

,cdTimestamp,Location_ID,Latitude,Longitude,LULC_Type,Temperature,Humidity,Wind_Speed,Solar_Radiation,Precipitation,Air_Pressure,NDVI,date,time
0,2022-01-01 00:00:00,Station_1,42.920785,-70.442076,Agricultural,-1.45,30.99,1.03,747.73,9,980.36,0.87,2022-01-01,00:00:00
1,2022-01-01 00:05:00,Station_1,45.878954,-88.553180,Forest,24.93,58.33,9.05,297.29,0,1020.30,0.56,2022-01-01,00:05:00
2,2022-01-01 00:10:00,Station_1,32.147619,-91.387175,Agricultural,20.60,74.46,8.63,549.58,2,1024.56,0.52,2022-01-01,00:10:00
3,2022-01-01 00:15:00,Station_1,26.725934,-114.654620,Barren,3.09,65.30,7.90,755.51,10,1043.17,0.46,2022-01-01,00:15:00
4,2022-01-01 00:20:00,Station_1,40.877759,-92.345482,Barren,17.44,44.88,11.49,979.98,1,998.33,0.47,2022-01-01,00:20:00
5,2022-01-01 00:25:00,Station_1,36.820347,-116.396554,Urban,4.62,74.19,12.63,786.51,4,1003.35,0.29,2022-01-01,00:25:00
6,2022-01-01 00:30:00,Station_1,41.571125,-70.232583,Water,32.39,31.06,2.31,769.45,9,1041.41,0.66,2022-01-01,00:30:00
7,2022-01-01 00:35:00,Station_1,36.388391,-97.529005,Barren,28.13,56.94,7.91,725.82,1,992.23,0.81,2022-01-01,00:35:00
8,2022-01-01 00:40:00,Station_1,44.465466,-75.302789,Agricultural,-1.87,48.09,12.74,462.53,9,1025.07,0.10,2022-01-01,00:40:00
9,2022-01-01 00:45:00,Station_1,43.169955,-70.523570,Water,8.16,68.57,1.43,694.18,8,990.57,0.76,2022-01-01,00:45:00
10,2022-01-01 00:50:00,Station_1,44.664592,-122.719303,Barren,-9.98,63.97,2.93,419.29,4,988.11,0.63,2022-01-01,00:50:00
11,2022-01-01 00:55:00,Station_1,43.239140,-104.357194,Agricultural,1.23,34.44,11.41,853.36,7,984.88,0.76,2022-01-01,00:55:00
12,2022-01-01 01:00:00,Station_1,33.396414,-86.678518,Forest,5.54,74.11,12.00,256.74,6,1044.21,0.35,2022-01-01,01:00:00
13,2022-01-01 01:05:00,Station_1,47.026284,-89.019727,Urban,12.15,68.55,13.21,908.97,6,1038.39,0.62,2022-01-01,01:05:00
14,2022-01-01 01:10:00,Station_1,31.948236,-73.766292,Barren,1.21,39.06,0.64,885.92,8,1013.24,0.38,2022-01-01,01:10:00
15,2022-01-01 01:15:00,Station_1,28.364658,-93.465580,Agricultural,8.46,58.06,14.42,786.53,3,1031.43,0.19,2022-01-01,01:15:00
16,2022-01-01 01:20:00,Station_1,28.772022,-61.177082,Agricultural,0.19,85.25,3.40,855.94,4,982.76,0.31,2022-01-01,01:20:00
17,2022-01-01 01:25:00,Station_1,28.334318,-81.227464,Urban,5.77,73.83,12.65,885.55,6,1006.10,0.70,2022-01-01,01:25:00
18,2022-01-01 01:30:00,Station_1,48.278136,-69.221530,Water,25.00,49.63,0.06,656.65,5,1027.96,0.55,2022-01-01,01:30:00
19,2022-01-01 01:35:00,Station_1,40.537528,-65.412920,Water,28.84,49.26,2.59,900.45,7,1027.42,0.71,2022-01-01,01:35:00

In [47]:
df.to_csv("../dataset/processed/cleanedDataset.csv")